-- =====================================================================
-- V1 :: Core schema for the URL shortener (H2)
--
-- Flyway guarantees this script runs exactly once per database
-- (tracked in the flyway_schema_history table). Every statement is
-- additionally written with IF NOT EXISTS so the script is safe to
-- replay by hand against an already-provisioned database.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Short code sequence.
-- Short codes are base62(scramble(nextval)) which gives collision-free,
-- non-sequential-looking codes without a read-before-write.
-- Starting at 100000 keeps generated codes at 6 characters.
-- ---------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS short_code_seq START WITH 100000 INCREMENT BY 1;

-- ---------------------------------------------------------------------
-- short_url :: one row per shortened link
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS short_url (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code       VARCHAR(32)   NOT NULL,
    original_url     VARCHAR(2048) NOT NULL,
    url_hash         VARCHAR(64)   NOT NULL,
    idempotency_key  VARCHAR(128),
    created_by       VARCHAR(128),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at       TIMESTAMP WITH TIME ZONE,
    last_accessed_at TIMESTAMP WITH TIME ZONE,
    active           BOOLEAN       NOT NULL DEFAULT TRUE,
    total_clicks     BIGINT        NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_short_url_short_code      ON short_url (short_code);
CREATE INDEX        IF NOT EXISTS ix_short_url_idempotency_key ON short_url (idempotency_key);
CREATE INDEX        IF NOT EXISTS ix_short_url_url_hash        ON short_url (url_hash);
CREATE INDEX        IF NOT EXISTS ix_short_url_active          ON short_url (active);
CREATE INDEX        IF NOT EXISTS ix_short_url_created_at      ON short_url (created_at);

-- ---------------------------------------------------------------------
-- click_event :: append-only analytics fact table, one row per redirect
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS click_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url_id  BIGINT      NOT NULL,
    short_code    VARCHAR(32) NOT NULL,
    clicked_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    ip_address    VARCHAR(64),
    user_agent    VARCHAR(512),
    referer       VARCHAR(512),
    device_type   VARCHAR(32),
    CONSTRAINT fk_click_event_short_url FOREIGN KEY (short_url_id)
        REFERENCES short_url (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_click_event_short_url_id ON click_event (short_url_id);
CREATE INDEX IF NOT EXISTS ix_click_event_short_code   ON click_event (short_code);
CREATE INDEX IF NOT EXISTS ix_click_event_clicked_at   ON click_event (clicked_at);
